version: 2.1
orbs:
  terraform: circleci/terraform@2.0.1

executors:
  node-executor:
    docker:
      - image: cimg/node:16.14.2
    working_directory: ~/repo

jobs:
  checkout_code_TODO:
    executor: node-executor
    steps:
      - run: |
          echo "1.1.$CIRCLE_BUILD_NUM" > ~/workspace/version
      - persist_to_workspace:
          root: ~/workspace
          paths: version
      - save_cache:
          paths:
            - ~/repo
          key: repo-{{ .Environment.CIRCLE_SHA1 }}
  build:
    executor: node-executor
    environment:
      AWS_REGION: ap-southeast-1
    steps:
      - restore_cache:
          keys:
            - repo-{{ .Environment.CIRCLE_SHA1 }}
      - attach_workspace:
          at: ~/workspace
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: build_and_push
          command: |
            cat ~/workspace/version > ./version
            TAG=$(cat ~/workspace/version)
            IMAGE_NAME=simple-node-js

            docker build -t "$IMAGE_NAME:$TAG" -t "$IMAGE_NAME:latest"


workflows:
  version: 2
  build-and-deploy:
    jobs:
      - checkout_code_TODO
      - build:
          requires:
            - checkout_code_TODO